apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-02T14:52:04Z"
  name: my-go-app-svc
  namespace: default
  resourceVersion: "570"
  uid: f444ea8e-82f0-414f-a5f4-9c321891a425
spec:
  clusterIP: 10.107.205.184
  clusterIPs:
  - 10.107.205.184
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31766
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: my-go-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
